---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  database-url: "bXlzcWw6Ly9sb2NhbGhvc3Q6MzMwNi9teWRiCg=="
  api-key: "dGVzdC1hcGkta2V5LTEyMwo="
  config-token: "dGVzdC10b2tlbi00NTYK"
