---
apiVersion: v1
kind: Service
metadata:
  name: multi-port-service
spec:
  selector:
    app: bunny
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  type: LoadBalancer
